### ISSUE TITLE
When running scene-graph-tf : TypeError: __int__ returned non-int (type NoneType)

### ISSUE THREAD

**Issue by ZhpeWarren** [danfeiX/scene-graph-TF-release#11]
When I follow the introduction and run the test demo :
./experiments/scripts/test.sh mini-vg -1 \
                              dual_graph_vrd_final 2 \
                              checkpoints/dual_graph_vrd_final_iter2.ckpt \
                              viz_cls \
                              0
I meet with the error : "TypeError: __int__ returned non-int (type NoneType) "
Here is the log, Are there any friends who can help?

  ./experiments/scripts/test.sh mini-vg -1 dual_graph_vrd_final 2 checkpoints/dual_graph_vrd_final_iter2.ckpt viz_cls 0
++ set -e
++ export PYTHONUNBUFFERED=True
++ PYTHONUNBUFFERED=True
++ DATASET=mini-vg
++ NUM_IM=-1
++ NET=dual_graph_vrd_final
++ INFERENCE_ITER=2
++ WEIGHT_FN=checkpoints/dual_graph_vrd_final_iter2.ckpt
++ TEST_MODE=viz_cls
++ GPU_ID=0
++ CFG_FILE=experiments/cfgs/sparse_graph.yml
++ case $DATASET in
++ ROIDB=mini_VG-SGG
++ RPNDB=mini_proposals
++ IMDB=mini_imdb_1024
++ export CUDA_VISIBLE_DEVICES=0
++ CUDA_VISIBLE_DEVICES=0
++ python ./tools/test_net.py --gpu 0 --weights checkpoints/dual_graph_vrd_final_iter2.ckpt --imdb mini_imdb_1024.h5 --roidb mini_VG-SGG --rpndb mini_proposals.h5 --cfg experiments/cfgs/sparse_graph.yml --network dual_graph_vrd_final --inference_iter 2 --test_size -1 --test_mode viz_cls
Called with args:
Namespace(cfg_file='experiments/cfgs/sparse_graph.yml', gpu_id=0, imdb='mini_imdb_1024.h5', inference_iter=2, model='checkpoints/dual_graph_vrd_final_iter2.ckpt', network_name='dual_graph_vrd_final', output_dir=None, roidb='mini_VG-SGG', rpndb='mini_proposals.h5', test_mode='viz_cls', test_size=-1, wait=True)
Using config:
{'DATA_DIR': '/share/UserFolder/zhpe/scene-graph-TF-release-master/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'GPU_ID': 0,
 'PIXEL_MEANS': array([[[ 102.9801,  115.9465,  122.7717]]]),
 'RNG_SEED': 3,
 'ROOT_DIR': '/share/UserFolder/zhpe/scene-graph-TF-release-master',
 'TEST': {'BBOX_REG': True,
          'FG_THRESH': 0.5,
          'HAS_RPN': False,
          'INFERENCE_ITER': 2,
          'MAX_SIZE': 1000,
          'NUM_PROPOSALS': 50,
          'PROPOSAL_NMS': 0.3,
          'SCALES': [600],
          'USE_RPN_DB': True},
 'TRAIN': {'ASPECT_GROUPING': True,
           'BATCH_SIZE': 256,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': False,
           'BBOX_REG': True,
           'BBOX_TARGET_NORMALIZATION_FILE': 'data/vg/bbox_distribution.npy',
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.1,
           'DISPLAY_FREQ': 10,
           'FG_FRACTION': 0.5,
           'FG_THRESH': 0.5,
           'GAMMA': 0.1,
           'IMS_PER_BATCH': 2,
           'LEARNING_RATE': 0.001,
           'MAX_SIZE': 1000,
           'MOMENTUM': 0.9,
           'NUM_NEG_RELS': 128,
           'SCALES': [600],
           'SNAPSHOT_FREQ': 50000,
           'SNAPSHOT_INFIX': '',
           'SNAPSHOT_PREFIX': '',
           'STEPSIZE': 50000,
           'SUMMARY_FREQ': 250,
           'USE_FLIPPED': True,
           'USE_RPN_DB': True},
 'VG_DIR': '/share/UserFolder/zhpe/scene-graph-TF-release-master/data/vg'}
/gpu:0
split==2
2017-09-17 16:20:56.154149: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-17 16:20:56.154186: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-17 16:20:56.154194: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-17 16:20:56.154200: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-17 16:20:56.154206: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-09-17 16:20:57.936868: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: TITAN X (Pascal)
major: 6 minor: 1 memoryClockRate (GHz) 1.531
pciBusID 0000:02:00.0
Total memory: 11.90GiB
Free memory: 11.75GiB
2017-09-17 16:20:57.936961: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2017-09-17 16:20:57.936981: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2017-09-17 16:20:57.937028: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:02:00.0)
Tensor("ims:0", shape=(?, ?, ?, 3), dtype=float32)
Tensor("conv_out:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rois:0", shape=(?, 5), dtype=float32)
[<tf.Tensor 'conv_out:0' shape=(?, ?, ?, 512) dtype=float32>, <tf.Tensor 'rois:0' shape=(?, 5) dtype=float32>]
<unknown>
Traceback (most recent call last):
  File "./tools/test_net.py", line 91, in <module>
    viz_net(args.network_name, args.model, imdb, args.test_mode)
  File "/share/UserFolder/zhpe/scene-graph-TF-release-master/tools/../lib/fast_rcnn/visualize.py", line 111, in viz_net
    net.setup()
  File "/share/UserFolder/zhpe/scene-graph-TF-release-master/tools/../lib/networks/models.py", line 179, in setup
    self._vgg_fc()
  File "/share/UserFolder/zhpe/scene-graph-TF-release-master/tools/../lib/networks/models.py", line 58, in _vgg_fc
    .fc(4096, name='fc6')
  File "/share/UserFolder/zhpe/scene-graph-TF-release-master/tools/../lib/networks/network.py", line 25, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/share/UserFolder/zhpe/scene-graph-TF-release-master/tools/../lib/networks/network.py", line 222, in fc
    feed_in, dim = (input, int(input_shape[-1]))
TypeError: __int__ returned non-int (type NoneType)

**Comment by ZhpeWarren** [comment]
The version of my tensorflow is 1.2.1.
I have followed the suggestion #1  to fix the error "ops.RegisterShape rather than tf.RegisterShape in roi_pooling_op_grad.py"

**Comment by ZhpeWarren** [comment]
I have solved it by lowering the version of tensorflow

**Comment by henbucuoshanghai** [comment]
how to lower the type of tf?
besides this,other ways to solve thin problem?
