### ISSUE TITLE
Unable to run: errors seemingly related to roidb data preparation

### ISSUE THREAD

**Issue by xzl8028** [danfeiX/scene-graph-TF-release#2]
Dear Danfei,

I keep running into the following errors when using the code. Could you help with this issue please?
***********************************************
/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients.py:90: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dl/scene-graph-TF-master/tools/../lib/roi_data_layer/data_runner.py", line 37, in _worker_main
    sample = self._task_func(task)
  File "/home/dl/scene-graph-TF-master/tools/../lib/roi_data_layer/layer.py", line 53, in _get_next_minibatch
    self.bbox_stds)
  File "/home/dl/scene-graph-TF-master/tools/../lib/roi_data_layer/roidb.py", line 83, in add_bbox_regression_targets
    num_classes = roidb[0]['gt_overlaps'].shape[1]
IndexError: list index out of range
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Loading pretrained model weights from data/pretrained/coco_vgg16_faster_rcnn_final.npy
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dl/scene-graph-TF-master/tools/../lib/roi_data_layer/data_runner.py", line 37, in _worker_main
    sample = self._task_func(task)
  File "/home/dl/scene-graph-TF-master/tools/../lib/roi_data_layer/layer.py", line 53, in _get_next_minibatch
    self.bbox_stds)
  File "/home/dl/scene-graph-TF-master/tools/../lib/roi_data_layer/roidb.py", line 83, in add_bbox_regression_targets
    num_classes = roidb[0]['gt_overlaps'].shape[1]
IndexError: list index out of range
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dl/scene-graph-TF-master/tools/../lib/roi_data_layer/data_runner.py", line 37, in _worker_main
    sample = self._task_func(task)
  File "/home/dl/scene-graph-TF-master/tools/../lib/roi_data_layer/layer.py", line 53, in _get_next_minibatch
    self.bbox_stds)
  File "/home/dl/scene-graph-TF-master/tools/../lib/roi_data_layer/roidb.py", line 83, in add_bbox_regression_targets
    num_classes = roidb[0]['gt_overlaps'].shape[1]
IndexError: list index out of range
***********************************************

This is what I did:
1. download the repository (denote the path as SG_ROOT), the 'mini-vg' dataset (plus the additional bbox_distribution.npy), rename it as 'vg' and place it under [SG_ROOT]/data/
2. 'make' it accodingly, and specify the 'filename' in roi_pooling_op.py to the absolute address '../roi_pooling_op_gpu_cuda8.so' for correct tf.load_op_library (no NotFoundError occured)
3. download 'coco_vgg16_faster_rcnn_final.npy' and place it under [SG_ROOT]/data/pretrained/
3. hit '[SG_ROOT]/experiments/scripts/train.sh dual_graph_vrd_final 2 checkpoints 0' 

FYI, I am using tensorflow 0.11.0 with CUDA 8.0.

Could you please give a clue on how to fix this issue? Thanks very much!

**Comment by xzl8028** [comment]
Dear Danfei,

After spending two days working on your code, I think the problem arises from the data preparation part, where the roidb preparation was not properly triggered, with imdb.roidb = [] just before fast_rcnn.train.train_net operation. 

Also, I think there are several parts that could be modified for better code clarity and re-usability. Please point me out if I had any misunderstandings:
1. the current data path config includes cfg.DATA_DIR = 'data',  cfg.VG_DIR = 'data/vg', cfg.TRAIN.BBOX_TARGET_NORMALIZATION_FILE = 'data/vg/bbox_distribution.npy' specified in [lib\fast_rcnn\config.py], whereas the data file names are obtained from user input in [tools/train_net.py], with cfg.TRAIN.INFERENCE_ITER = args.inference_iter, also in [tools/train_net.py]. Then there is another config file in [experiments/cfgs/sparse_graph.yml]. ------------------ it might be better to organise them together at a single location. 

2. keywords like imdb/roidb seem to be associated with several closely-related things, sometimes as the imdb/roidb FILE (e.g. lines 37&40 in [tools/train_net.py]), or as the imdb/roidb OBJECT (e.g. lines 81&88 in [tools/train_net.py] and lines 64&87 [tools/imdb.py]), and other times as the imdb/roidb FUNCTION (e.g. line 48 in [tools/imdb.py]), or as the roi_data_layer.roidb MODULE (e.g. line 179 in [tools/vg_hdf5.py]) --------------- which can be really difficult to read. It might be better to choose slighly different names in these cases. 

3. After object creation, the imdb has a number of repititive field variables, e.g. imdb._roidb +imdb.roidb, imdb._num_classes + imdb.num_classes, imdb._name + imdb.name, which however output different values, making it really confusing to follow...

I understand making all such modifications can be quite time-consuming, therefore I would be more than grateful if you could make a quick modification so that the code can run directly after stright downloading. Many thanks for your support.

**Comment by xzl8028** [comment]
It seems changing 'split = 0' to 'split = 2' helps solve this problem, after which the roidb is no longer empty as before. However, a new problem arises...with the following error message:
************************************
overriding layer rel_score!!!!
/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients.py:90: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Loading pretrained model weights from data/pretrained/coco_vgg16_faster_rcnn_final.npy
/usr/local/lib/python2.7/dist-packages/scipy/ndimage/interpolation.py:600: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xzl/scene-graph-TF-master/tools/../lib/roi_data_layer/data_runner.py", line 37, in _worker_main
    sample = self._task_func(task)
  File "/home/xzl/scene-graph-TF-master/tools/../lib/roi_data_layer/layer.py", line 55, in _get_next_minibatch
    blobs = get_minibatch(minibatch_db, self._num_classes)
  File "/home/xzl/scene-graph-TF-master/tools/../lib/roi_data_layer/minibatch.py", line 53, in get_minibatch
    num_neg_rels=cfg.TRAIN.NUM_NEG_RELS)
  File "/home/xzl/scene-graph-TF-master/tools/../lib/roi_data_layer/minibatch.py", line 204, in _sample_graph
    replace=False)
  File "mtrand.pyx", line 1176, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:18822)
TypeError: 'numpy.float64' object cannot be interpreted as an index
conv5_1
fc6
/usr/local/lib/python2.7/dist-packages/scipy/ndimage/interpolation.py:600: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
conv5_3
fc7
conv5_2
conv4_1
conv4_2
conv4_3
conv3_3
conv3_2
conv3_1
conv1_1
conv1_2
conv2_2
conv2_1
qlen=3
iter: 1 / 150000, lr: 0.001000, loss_box: 1.133357, loss_cls: 5.017276, loss_total: 7.662880, loss_rel: 1.512247
************************************
Alternatively, if I choose not to use the downloaded bbox_distribution.npy, but to re-compute it by turning line 93  in tools/train_net.py to True. It leads to a different error message as below:
************************************
overriding layer rel_score!!!!
/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients.py:90: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Loading pretrained model weights from data/pretrained/coco_vgg16_faster_rcnn_final.npy
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xzl/scene-graph-TF-master/tools/../lib/roi_data_layer/data_runner.py", line 37, in _worker_main
    sample = self._task_func(task)
  File "/home/xzl/scene-graph-TF-master/tools/../lib/roi_data_layer/layer.py", line 51, in _get_next_minibatch
    prepare_roidb(minibatch_db)
  File "/home/xzl/scene-graph-TF-master/tools/../lib/roi_data_layer/roidb.py", line 37, in prepare_roidb
    assert all(max_classes[nonzero_inds] != 0)
AssertionError
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xzl/scene-graph-TF-master/tools/../lib/roi_data_layer/data_runner.py", line 37, in _worker_main
    sample = self._task_func(task)
  File "/home/xzl/scene-graph-TF-master/tools/../lib/roi_data_layer/layer.py", line 51, in _get_next_minibatch
    prepare_roidb(minibatch_db)
  File "/home/xzl/scene-graph-TF-master/tools/../lib/roi_data_layer/roidb.py", line 37, in prepare_roidb
    assert all(max_classes[nonzero_inds] != 0)
AssertionError
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xzl/scene-graph-TF-master/tools/../lib/roi_data_layer/data_runner.py", line 37, in _worker_main
    sample = self._task_func(task)
  File "/home/xzl/scene-graph-TF-master/tools/../lib/roi_data_layer/layer.py", line 51, in _get_next_minibatch
    prepare_roidb(minibatch_db)
  File "/home/xzl/scene-graph-TF-master/tools/../lib/roi_data_layer/roidb.py", line 37, in prepare_roidb
    assert all(max_classes[nonzero_inds] != 0)
AssertionError
conv5_1
fc6
conv5_3
fc7
conv5_2
conv4_1
conv4_2
conv4_3
conv3_3
conv3_2
conv3_1
conv1_1
conv1_2
conv2_2
conv2_1
qlen=0
************************************
It would be really great if you would be able to help with my long-running debugging process...Thanks very much...

**Comment by danfeiX** [comment]
Hi,

Sorry to hear that you ran into so many issues.

1. It seems like you are trying to train a model. Have you created the image database? The framework reads in an hdf5 image database as input. You may refer to the dataset section on how to create one. As explained in the README doc, the mini vg dataset is only for evaluation, not for training.

2. The naming is simply inherited from the pyfaster-rcnn repository. I'm sorry you find that confusing. I'm in the middle of paper submission and I'll see if I can find some time to make the changes later this month.

Danfei

**Comment by yanxp** [comment]
@xzl8028  assert all(max_classes[nonzero_inds] != 0)
AssertionError
Have you solve the problem when re-compute .
