### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by ginlock** [danfeiX/scene-graph-TF-release#33]
Traceback (most recent call last):
  File "./tools/train_net.py", line 86, in <module>
    imdb= get_imdb(args.roidb, args.imdb, args.rpndb, split=0)
  File "/home/duan/anaconda2/envs/tf/z/scene-graph-TF-release-master/tools/../lib/datasets/factory.py", line 10, in get_imdb
    return vg_hdf5('%s.h5'%roidb_name, '%s-dicts.json'%roidb_name, imdb_name, rpndb_name, split=split, num_im=num_im)
  File "/home/duan/anaconda2/envs/tf/z/scene-graph-TF-release-master/tools/../lib/datasets/vg_hdf5.py", line 42, in __init__
    self.im_sizes = np.vstack([self.im_h5['image_widths'][split_mask],
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/duan/anaconda2/envs/tf/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 535, in __getitem__
    if args == (Ellipsis,) or args == tuple():

**Comment by ginlock** [comment]
@danfeiX

**Comment by danfeiX** [comment]
Seems like an issue with hdf5 loading. Which dataset are you using?

**Comment by ginlock** [comment]
I used visual genome datasets to generate the imdb files, and download other files. Did I make some mistakes while running the create_imdb.sh script file? what's more, I want to know is there any way to run this project on picture directly?

**Comment by ginlock** [comment]
I have solved this problem. I made a mistake when generating the imdb files. Thank you for your help.

**Comment by jgyy4775** [comment]
@ginlock  Wath's the problem??

please help me...

**Comment by sangminwoo** [comment]
@ginlock I have a same issue. could you please tell us what was the problem is? thanks.

**Comment by hetong007** [comment]
Hi All, I also met this issue and solved it by:

- unzip everything
- move all images from `VG_100K` and `VG_100K_2` to `VG/images` folder, i.e. the script expect to read `VG/images/1024.jpg`.

Please check if your `imdb_1024.h5` has size around 317G.
