### ISSUE TITLE
OOM during VG training

### ISSUE THREAD

**Issue by emreyak** [danfeiX/scene-graph-TF-release#37]
Hi @danfeiX and everyone,

I'm running into out-of-memory errors during training on the complete VG dataset. Given the 150k iterations recommended, each of the workers crashes with the same error (below) at various iterations in the training process. The last worker survives until about 58k iterations, after which the program freezes and produces no further output.

The error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/../scene-graph-TF-release/tools/../lib/roi_data_layer/data_runner.py", line 37, in _worker_main
    sample = self._task_func(task)
  File "/../scene-graph-TF-release/tools/../lib/roi_data_layer/layer.py", line 50, in _get_next_minibatch
    minibatch_db = self.imdb.add_rpn_rois(minibatch_db)
  File "/../scene-graph-TF-release/tools/../lib/datasets/vg_hdf5.py",
 line 159, in add_rpn_rois
    rpn_roidb = self._load_rpn_roidb(gt_roidb)
  File "/../scene-graph-TF-release/tools/../lib/datasets/vg_hdf5.py",
 line 173, in _load_rpn_roidb
    roidb = self.create_roidb_from_box_list(box_list, gt_roidb)
  File "/../scene-graph-TF-release/tools/../lib/datasets/imdb.py", line 73, in create_roidb_from_box_list
    gt_boxes.astype(np.float))
  File "utils/bbox.pyx", line 29, in utils.cython_bbox.bbox_overlaps
    cdef np.ndarray[DTYPE_t, ndim=2] overlaps = np.zeros((N, K), dtype=DTYPE)
MemoryError
```

What I have tried:
- Decreasing the batch size
- Ensuring that tf.ConfigProto().gpu_options.allow_growth is set to True

Specs:
CPU: Intel Xeon CPU E5-2698 v4 @ 2.20GHz
GPU: Tesla V100-SXM2-16GB
RAM: 500 GB

My questions:
- Does anyone have a solution for this?
- If not, does anyone know if a model checkpoint obtained at ~49k iterations would be sufficient? How much performance improvement is gained over those last 100k iterations?
- Is anyone able to train this model? If so, what are the specs of your machine?

Thank you for your time! I would greatly appreciate any answers or comments. I will update this if I have any insights.

**Comment by emreyak** [comment]
Fixed this, and I can confirm that I can now train on the complete VG dataset up to the default 150,000 iterations. The whole process used no more than 30GB of RAM.

The MemoryError was happening because of an error in the multiprocessing in data_runner.py. Basically, processes were not being periodically refreshed and would thus slowly accumulate memory over the lifetime of the program without ever releasing it.

By occasionally killing processes and spawning new ones to pick up where they left off, I was able to circumvent this problem.
