### ISSUE TITLE
 OSError: [Errno 2] No such file or directory--subprocess.Popen(['xdg-open', filepath])

### ISSUE THREAD

**Issue by smartcai** [danfeiX/scene-graph-TF-release#43]
hi, could u help me solve this problem, tks very much! @danfeiX 

Loading model weights from checkpoints/dual_graph_vrd_final_iter2.ckpt
=======================VIZ INFERENCE Iteration =  1
=======================VIZ MODES =  viz_det
Traceback (most recent call last):
  File "./tools/test_net.py", line 91, in <module>
    viz_net(args.network_name, args.model, imdb, args.test_mode)
  File "/data/scene-graph-TF-release/tools/../lib/fast_rcnn/visualize.py", line 163,in viz_net
    gt_to_pred, roidb[im_i])
  File "/data/scene-graph-TF-release/tools/../lib/fast_rcnn/visualize.py", line 69, in draw_graph_pred
    **graph_dict = draw_scene_graph(cls_pred, pred_inds, rel_pred)**
  File "/data/scene-graph-TF-release/tools/../lib/datasets/viz.py", line 29, in draw_scene_graph
    return draw_graph(viz_labels, viz_rels, cfg)
  File "/data/scene-graph-TF-release/tools/../lib/datasets/viz.py", line 63, in draw_graph
    u.view()
  File "/usr/local/miniconda3/envs/dl/lib/python2.7/site-packages/graphviz/files.py", line 203, in view
    cleanup=cleanup)
  File "/usr/local/miniconda3/envs/dl/lib/python2.7/site-packages/graphviz/files.py", line 182, in render
    self._view(rendered, self._format)
  File "/usr/local/miniconda3/envs/dl/lib/python2.7/site-packages/graphviz/files.py", line 218, in _view
    **view_method(filepath)**
  File "/usr/local/miniconda3/envs/dl/lib/python2.7/site-packages/graphviz/backend.py", line 228, in view_unixoid
    subprocess.Popen(['xdg-open', filepath])
  File "/usr/local/miniconda3/envs/dl/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/miniconda3/envs/dl/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
**OSError: [Errno 2] No such file or directory**

**Comment by williamwangus** [comment]
I have the same error, did you fine any solution?
